name: sms

services:
  api:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    container_name: sms-api
    ports:
      - "8080:8080"
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./apps/backend:/app
      - /app/tmp
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    container_name: sms-web
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: sms-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sms
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
