FROM golang:1.26.1-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 5000

CMD ["sh", "./entrypoint.sh"]