CREATE TABLE students (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id     UUID NOT NULL UNIQUE,
    reference_no   VARCHAR NOT NULL UNIQUE,
    fiscal_year    VARCHAR NOT NULL,
    serial_no      INTEGER NOT NULL,
    full_name      VARCHAR NOT NULL,
    dob            DATE NOT NULL,
    gender         VARCHAR NOT NULL,
    phone          VARCHAR NOT NULL UNIQUE,
    address        TEXT NOT NULL,
    guardian_name  VARCHAR NOT NULL,
    guardian_phone VARCHAR NOT NULL,
    photo_url      VARCHAR,
    source         VARCHAR NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'completed', 'rejected')),
    notes          TEXT,
    shift          TEXT NOT NULL DEFAULT 'morning' CHECK (shift IN ('morning','day','evening')),
    shift_time     TEXT NOT NULL,
    batch          TEXT,
    rejection_reason TEXT,
    updated_at TIMESTAMPTZ NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_serial_per_fiscal_year UNIQUE (fiscal_year, serial_no)
);