ALTER TABLE stock_in ALTER COLUMN qty TYPE INTEGER USING ROUND(qty)::INTEGER;
ALTER TABLE stock_out ALTER COLUMN qty TYPE INTEGER USING ROUND(qty)::INTEGER;
ALTER TABLE wastage ALTER COLUMN qty TYPE INTEGER USING ROUND(qty)::INTEGER;
